
services:
  base:
    image: base-${WAZUH_DASHBOARD_BRANCH}-${WAZUH_SECURITY_PLUGIN_BRANCH}-${WAZUH_DASHBOARD_PLUGINS_BRANCH}-${ARCHITECTURE}
    build:
      context: .
      dockerfile: base-packages.Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        WAZUH_DASHBOARD_BRANCH: ${WAZUH_DASHBOARD_BRANCH}
        WAZUH_DASHBOARD_SECURITY_BRANCH: ${WAZUH_SECURITY_PLUGIN_BRANCH}
        WAZUH_DASHBOARD_PLUGINS_BRANCH: ${WAZUH_DASHBOARD_PLUGINS_BRANCH}
        ARCHITECTURE: ${ARCHITECTURE}
    container_name: base-${WAZUH_DASHBOARD_BRANCH}-${WAZUH_SECURITY_PLUGIN_BRANCH}-${WAZUH_DASHBOARD_PLUGINS_BRANCH}-${ARCHITECTURE}
    environment:
      OPENSEARCH_DASHBOARDS_VERSION: 2.19.1
    volumes:
      - ./:/home/node/output
    command: >
      bash -c '
        cp -r /home/node/packages /home/node/output
      '
